m5_pipeline:          # debe coincidir con profile: en dbt_project.yml
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: SILVER
      private_key_path: /secrets/rsa_key.p8   # ruta DENTRO del contenedor (montada en docker-compose)
      threads: 4
